// ---------- ESLint rules ---------------------------------
// import with {type: 'json'} added in FF138
export const rules = {
  // https://github.com/eslint/eslint/blob/main/packages/js/src/configs/eslint-recommended.js
  recommended: {
    // updated for v10.0.0
    "constructor-super": "error",
    "for-direction": "error",
    "getter-return": "error",
    "no-async-promise-executor": "error",
    "no-case-declarations": "error",
    "no-class-assign": "error",
    "no-compare-neg-zero": "error",
    "no-cond-assign": "error",
    "no-const-assign": "error",
    "no-constant-binary-expression": "error",
    "no-constant-condition": "error",
    "no-control-regex": "error",
    "no-debugger": "error",
    "no-delete-var": "error",
    "no-dupe-args": "error",
    "no-dupe-class-members": "error",
    "no-dupe-else-if": "error",
    "no-dupe-keys": "error",
    "no-duplicate-case": "error",
    "no-empty": "error",
    "no-empty-character-class": "error",
    "no-empty-pattern": "error",
    "no-empty-static-block": "error",
    "no-ex-assign": "error",
    "no-extra-boolean-cast": "error",
    "no-fallthrough": "error",
    "no-func-assign": "error",
    "no-global-assign": "error",
    "no-import-assign": "error",
    "no-invalid-regexp": "error",
    "no-irregular-whitespace": "error",
    "no-loss-of-precision": "error",
    "no-misleading-character-class": "error",
    "no-new-native-nonconstructor": "error",
    "no-nonoctal-decimal-escape": "error",
    "no-obj-calls": "error",
    "no-octal": "error",
    "no-prototype-builtins": "error",
    "no-redeclare": "error",
    "no-regex-spaces": "error",
    "no-self-assign": "error",
    "no-setter-return": "error",
    "no-shadow-restricted-names": "error",
    "no-sparse-arrays": "error",
    "no-this-before-super": "error",
    "no-unassigned-vars": "error",
    "no-undef": "error",
    "no-unexpected-multiline": "error",
    "no-unreachable": "error",
    "no-unsafe-finally": "error",
    "no-unsafe-negation": "error",
    "no-unsafe-optional-chaining": "error",
    "no-unused-labels": "error",
    "no-unused-private-class-members": "error",
    "no-unused-vars": "error",
    "no-useless-assignment": "error",
    "no-useless-backreference": "error",
    "no-useless-catch": "error",
    "no-useless-escape": "error",
    "no-with": "error",
    "preserve-caught-error": "error",
    "require-yield": "error",
    "use-isnan": "error",
    "valid-typeof": "error"
  },

  fireMonkey: {
    // --- userscripts override
    // e.g. Read-only global 'setTimeout' should not be modified.
    "no-global-assign": "off",

    // --- overrides
    "no-case-declarations": "off",
    "no-empty": ["warn", {allowEmptyCatch: true}],
    "no-fallthrough": ["error", {allowEmptyCase: true}],
    "no-sparse-arrays": "off",
    "no-unused-vars": ["error", {args: "none", ignoreClassWithStaticInitBlock: true}],

    // --- additions
    "camelcase": ["warn", {allow: ["^GM_"]}],
    "class-methods-use-this": "warn",
    "curly": "error",
    "dot-notation": "error",
    "eqeqeq": "error",
    "logical-assignment-operators": "warn",
    "max-depth": ["warn", 3],
    "no-array-constructor": "error",
    // "no-console": "warn",
    "no-duplicate-imports": "error",
    "no-else-return": "error",
    "no-eval": "error",
    "no-implied-eval": "error",
    "no-invalid-this": "error",
    "no-lone-blocks": "error",
    "no-lonely-if": "error",
    "no-multi-assign": "error",
    "no-new-func": "error",
    "no-new-wrappers": "error",
    "no-template-curly-in-string": "error",
    "no-unneeded-ternary": "error",
    "no-useless-computed-key": "error",
    "no-useless-concat": "error",
    "no-useless-return": "error",
    "no-var": "warn",
    "operator-assignment": "error",
    "prefer-const": ["warn", {destructuring: "all"}],
    "prefer-object-has-own": "error",
    "prefer-object-spread": "error",
    "prefer-spread": "error",
    "unicode-bom": "error",
    "yoda": "error",

    "no-restricted-properties": ["error", {
        "object": "GM",
        "allowProperties": ['info'],
        "message": "(missing @grant or unsupported)"
      },
    ],
  }
};